name: Build Tests

on: [push, pull_request]

env:
  COPR_REPO: ${{ vars.COPR_REPO || '@pki/11.4' }}

jobs:
  build-test:
    name: Build Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - 'fedora:39'
    container: ${{ matrix.os }}
    steps:
    - name: Clone repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        dnf install -y dnf-plugins-core rpm-build
        dnf copr enable -y $COPR_REPO
        dnf builddep -y --spec idm-console-framework.spec

    - name: Build IDM Console Framework
      run: ./build.sh
