name: Build Tests

on: [push, pull_request]

env:
  COPR_REPO: ${{ vars.COPR_REPO || '@pki/master' }}

jobs:
  init:
    name: Initialization
    uses: ./.github/workflows/init.yml
    secrets: inherit

  build-test:
    name: Build Test
    needs: init
    runs-on: ubuntu-latest
    container: ${{ needs.init.outputs.base-image }}
    steps:
    - name: Clone repository
      uses: actions/checkout@v2

    - name: Install build dependencies from Fedora
      run: |
        dnf install -y dnf-plugins-core moby-engine rpm-build
        if [ -n "$COPR_REPO" ]; then dnf copr enable -y $COPR_REPO; fi
        dnf builddep -y --skip-unavailable --spec idm-console-framework.spec

    - name: Import JSS packages from jss-dist
      run: |
        docker pull quay.io/dogtagpki/jss-dist:latest
        docker create --name=jss-dist quay.io/dogtagpki/jss-dist:latest
        docker cp jss-dist:/root/RPMS/. /tmp/RPMS/
        docker rm -f jss-dist

    - name: Import LDAP SDK packages from ldapjdk-dist
      run: |
        docker pull quay.io/dogtagpki/ldapjdk-dist:latest
        docker create --name=ldapjdk-dist quay.io/dogtagpki/ldapjdk-dist:latest
        docker cp ldapjdk-dist:/root/RPMS/. /tmp/RPMS/
        docker rm -f ldapjdk-dist

    - name: Install build dependencies from GitHub Packages
      run: |
        dnf localinstall -y /tmp/RPMS/*

    - name: Build with Ant
      run: ./build.sh

    - name: Install JSS into local Maven repo
      run: |
        # get JSS <major>.<minor>.<update> version
        JSS_VERSION=$(rpm -q --qf "%{version}" dogtag-jss)

        # if built by COPR, jss-base.jar will be installed in /usr/lib/java,
        # otherwise it will be in /usr/share/java.
        JSS_BASE_JAR=$(find /usr/lib/java /usr/share/java -name jss-base.jar)

        mvn install:install-file \
            -Dfile=$JSS_BASE_JAR \
            -DgroupId=org.dogtagpki.jss \
            -DartifactId=jss-base \
            -Dversion=$JSS_VERSION-SNAPSHOT \
            -Dpackaging=jar \
            -DgeneratePom=true

    - name: Install LDAP JDK into local Maven repo
      run: |
        # get LDAP JDK <major>.<minor>.<update> version
        LDAPJDK_VERSION=$(rpm -q --qf "%{version}" dogtag-ldapjdk)

        mvn install:install-file \
            -Dfile=/usr/share/java/ldapjdk.jar \
            -DgroupId=org.dogtagpki.ldap-sdk \
            -DartifactId=ldapjdk \
            -Dversion=$LDAPJDK_VERSION-SNAPSHOT \
            -Dpackaging=jar \
            -DgeneratePom=true

    - name: Build with Maven
      run: mvn package

    - name: Compare idm-console-framework.jar
      run: |
        jar tvf $HOME/build/idm-console-framework/release/jars/idm-console-framework.jar | awk '{print $8;}' | grep -v '/$' | sort | tee idm-console-framework.ant
        jar tvf target/idm-console-framework.jar | awk '{print $8;}' | grep -v -E '^META-INF/maven/|/$' | sort | tee idm-console-framework.maven
        diff idm-console-framework.ant idm-console-framework.maven
