name: Build Tests

on: [push, pull_request]

jobs:
  init:
    name: Initialization
    uses: ./.github/workflows/init.yml
    secrets: inherit

  build-test:
    name: Build Test
    needs: init
    runs-on: ubuntu-latest
    container: ${{ needs.init.outputs.base-image }}
    steps:
    - name: Clone repository
      uses: actions/checkout@v2

    - name: Install build dependencies from Fedora
      run: |
        dnf install -y dnf-plugins-core moby-engine rpm-build
        if [ -n "$COPR_REPO" ]; then dnf copr enable -y $COPR_REPO; fi
        dnf builddep -y --skip-unavailable --spec idm-console-framework.spec
      env:
        COPR_REPO: ${{ needs.init.outputs.repo }}

    - name: Import JSS packages from jss-dist
      run: |
        docker pull ghcr.io/dogtagpki/jss-dist:latest
        docker create --name=jss-dist ghcr.io/dogtagpki/jss-dist:latest
        docker cp jss-dist:/root/RPMS/. /tmp/RPMS/
        docker rm -f jss-dist

    - name: Import LDAP SDK packages from ldapjdk-dist
      run: |
        docker pull ghcr.io/dogtagpki/ldapjdk-dist:latest
        docker create --name=ldapjdk-dist ghcr.io/dogtagpki/ldapjdk-dist:latest
        docker cp ldapjdk-dist:/root/RPMS/. /tmp/RPMS/
        docker rm -f ldapjdk-dist

    - name: Install build dependencies from GitHub Packages
      run: |
        dnf localinstall -y /tmp/RPMS/*

    - name: Build IDM Console Framework
      run: ./build.sh
