name: Initialization
on:
  workflow_call:
    secrets:
      BASE64_DATABASE:
        required: false
    outputs:
      db-image:
        value: ${{ jobs.init.outputs.db-image }}

jobs:
  init:
    name: Initializing workflow
    runs-on: ubuntu-latest
    outputs:
      db-image: ${{ steps.init.outputs.db-image }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Initialize workflow
        id: init
        env:
          BASE64_DATABASE: ${{ secrets.BASE64_DATABASE }}
        run: |
          tests/bin/init-workflow.sh
