name: Publish IDM Console Framework

on:
  push:
    branches:
      - v2.1

env:
  NAMESPACE: ${{ vars.REGISTRY_NAMESPACE || github.repository_owner }}

jobs:
  publish-maven:
    if: vars.REGISTRY != ''
    name: Publishing Maven artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Check settings.xml
        run: |
          cat ~/.m2/settings.xml

      - name: Update pom.xml
        run: |
          sed -i \
              -e "s/OWNER/$NAMESPACE/g" \
              -e "s/REPOSITORY/idm-console-framework/g" \
              pom.xml
          cat pom.xml

      - name: Publish Maven artifacts
        run: |
          mvn \
              --batch-mode \
              --update-snapshots \
              deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  wait-for-images:
    if: vars.REGISTRY != ''
    name: Waiting for container images
    runs-on: ubuntu-latest
    steps:
      - name: Wait for container images
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.ref }}
          check-name: 'Building IDM Console Framework'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 30

  publish-images:
    name: Publishing container images
    needs: wait-for-images
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: vars.REGISTRY == 'ghcr.io'

      - name: Log in to other container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
        if: vars.REGISTRY != 'ghcr.io'

      - name: Retrieve IDM Console Framework images
        uses: actions/cache@v4
        with:
          key: idm-console-framework-images-${{ github.sha }}
          path: idm-console-framework-images.tar

      - name: Load IDM Console Framework images
        run: |
          docker load --input idm-console-framework-images.tar

      - name: Publish idm-console-framework-dist image
        run: |
          docker tag idm-console-framework-dist ${{ vars.REGISTRY }}/$NAMESPACE/idm-console-framework-dist:2.1
          docker push ${{ vars.REGISTRY }}/$NAMESPACE/idm-console-framework-dist:2.1
